import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/contexts/theme";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Search Engine",
  description: "Generated by create next app",
};

type Props = Readonly<{
  children: React.ReactNode;
}>;

const RootLayout = (props: Props) => {
  return (
    <html lang="zh-TW">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {props.children}
        </ThemeProvider>
      </body>
    </html>
  );
};

export default RootLayout;
